// OAUth
export const SET_TOKEN_VIA_OAUTH = 'SET_TOKEN_VIA_OAUTH'

//ABi
export const GET_ABI_CATALOG_RECORDS_BY_BARCODE = 'GET_ABI_CATALOG_RECORDS_BY_BARCODE'
export const GET_ABI_CATALOG_RECORDS = 'GET_ABI_CATALOG_RECORDS'
