// OAUth
export const SET_TOKEN_VIA_OAUTH = 'SET_TOKEN_VIA_OAUTH'

//ABi
export const GET_ABI_CATALOG_RECORDS_BY_BARCODE = 'GET_ABI_CATALOG_RECORDS_BY_BARCODE'
export const GET_ABI_CATALOG_RECORDS = 'GET_ABI_CATALOG_RECORDS'

export const GET_ABI_RELATED_PRODUCTS = 'GET_ABI_RELATED_PRODUCTS'
export const GET_ABI_EQUIVALENT_RECORDS = 'GET_ABI_EQUIVALENT_RECORDS'

export const GET_SITE_CATALOG_RECORDS = 'GET_SITE_CATALOG_RECORDS'

//System
export const GET_BRANCH_SERVICES_RECORDS = 'GET_BRANCH_SERVICES_RECORDS'
export const SET_SITES_FROM_BRANCH_SERVICES = 'SET_SITES_FROM_BRANCH_SERVICES'

//Barcode
export const SET_BARCODE = 'SET_BARCODE'